version: '3'

services:
  mysql:
    container_name: mysql_hosue_batch
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "house_batch"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"